### ISSUE TITLE
Estimation time period - 1 month

### ISSUE THREAD

**Issue by Gordonby** [TheCloudTheory/arm-estimator#105]
Not sure if i missed the option/docs on this, but i'd like my TotalCost estimate to be projected for the entire month.

Currently the output seems to be a combination of hour/month depending on the azure service.

See my estimate workflow run for more info: https://github.com/Gordonby/arm-estimator/actions/runs/3540823046

**Comment by kamil-mrzyglod** [comment]
Hey! As I understand you mean the actual metrics, which get reported when estimation is generated? For example:
```
[Create] pip-afw-priv
   \--- Type: Microsoft.Network/publicIPAddresses
   \--- Location: US East
   \--- Total cost: 3.65 USD
   \--- Delta: +3.65 USD

Aggregated metrics:

-> Standard | IP Addresses | Standard IPv4 Static Public IP | 0.005 for 1 Hour
```

For each metric, ACE performs an estimation for the full month, no matter if we're talking about month / hour metric. Detailed metric is reported "as is" based on unit price and unit of measure.  As I understand, you'd like to have an option to see full month projection even for detailed metrics? Something like that:

```
[Create] pip-afw-priv
   \--- Type: Microsoft.Network/publicIPAddresses
   \--- Location: US East
   \--- Total cost: 3.65 USD
   \--- Delta: +3.65 USD

Aggregated metrics:

-> Standard | IP Addresses | Standard IPv4 Static Public IP | 3.65 for 1 Month
```

**Comment by Gordonby** [comment]
If this is the case, that's great. 😃

Coupled with the estimate being a lot lower than i expected and the fact I couldn't easily see that from the output... i made the assumption it wasn't rolled up to the month.

![image](https://user-images.githubusercontent.com/17914476/204023917-b5cec753-ac93-4d86-aa18-93a922c4e1f5.png)

**Comment by kamil-mrzyglod** [comment]
In that case it definitely looks, like it isn't propagated for the full month. I did a quick check and it seems metrics are not correctly matched for AppGW. It should be fixed with the next release.

**Comment by kamil-mrzyglod** [comment]
Done. Beta6 release should be available over the weeked.

**Comment by kamil-mrzyglod** [comment]
Fixed in the `Beta6` release.
