### ISSUE TITLE
Inline params + Param file

### ISSUE THREAD

**Issue by Gordonby** [TheCloudTheory/arm-estimator#106]
It seems that ACE supports inline "instead of" parameters file.

1. I'd like to see the behaviour such that it works more like how the AZ CLI works, in that a Parameters file would be used as the base parameter set and then any inline parameters overrides.

2. I'd also prefer if that the syntax of passing multiple parameters was more similar to that of the AZ CLI. Instead of having to state `--inline` multiple times, i'd prefer the simpler approach AZ CLI has.

**Comment by kamil-mrzyglod** [comment]
Actually ACE is supposed to support both parameters file and inline parameters (see https://github.com/TheCloudTheory/arm-estimator#parameters-1). Do you mean, that when you provide both parameters file and inline parameters, parameters file is not treated as a base, which eventually can be overwritten by inline params? If so, do you have a repro for that?

Ad. 2 - could you elaborate on how Azure CLI differs in terms of providing parameters for deployment? If I remember correctly, in Azure CLI you still provide many `--parameter` options to pass inline parameters. Perhaps I've misunderstood your point :)

**Comment by Gordonby** [comment]
I was taking the documentation literally, i've not tested the behaviour.
![image](https://user-images.githubusercontent.com/17914476/203992519-54e42e49-f18c-4ff0-a335-40999529e04e.png)

The Azure CLI behaviour i'm used to is passing a `-p` then each parameter is seperated by a space
![image](https://user-images.githubusercontent.com/17914476/203992873-c1fb30f5-c39a-4b49-8ef9-63afe65a1e37.png)

The docs for ACE suggest using --inline multiple times
![image](https://user-images.githubusercontent.com/17914476/203993014-9d532d29-f2ee-4f50-a475-4ef9172f1ddd.png)

**Comment by kamil-mrzyglod** [comment]
Haha, so that's a little to literally ;) You can use both parameters file and inline params, you can do that without additional setup.

For passing inline params - got it. I see if it's possible to implement without lots of changes.

**Comment by Gordonby** [comment]
Great. I'll give the File + Inline a go 👍

**Comment by Gordonby** [comment]
Unfortunately it doesn't work how i'd hope.

If there's a duplicate then it won't override.

![image](https://user-images.githubusercontent.com/17914476/204052579-70fc220f-aa58-4af9-a798-537568a7c8eb.png)
