### ISSUE TITLE
Add support for Azure Kubernetes Service

### ISSUE THREAD

**Issue by Gordonby** [TheCloudTheory/arm-estimator#107]
![image](https://user-images.githubusercontent.com/17914476/203805443-bf7bfc41-87dc-486e-a723-cc1b6e3aa702.png)

**Comment by kamil-mrzyglod** [comment]
Could you provide a template you used for deployment?

**Comment by Gordonby** [comment]
> Could you provide a template you used for deployment?

      Template: https://github.com/Azure/AKS-Construction/releases/download/0.9.4/main.json
      Param file: https://raw.githubusercontent.com/Azure/AKS-Construction/main/.github/workflows_dep/AksDeploy-Private.parameters.json

**Comment by kamil-mrzyglod** [comment]
Fixed, will be released soon with 1.0 version.
![image](https://user-images.githubusercontent.com/11725731/208292240-201afbf9-89ab-493e-a9c6-f5cb5888dd62.png)
