### ISSUE TITLE
Add Summary Block in json output

### ISSUE THREAD

**Issue by Gordonby** [TheCloudTheory/arm-estimator#111]
In addition to Total Cost and Delta, i'd quite like;

1. Total Resource Count
2. Estimated Resource Count 
3. Skipped Resource Count (some resources may not be supported for estimate calculations)

![image](https://user-images.githubusercontent.com/17914476/204049587-d5d00dac-3bfd-4397-b7b6-ff9744ae566c.png)

**Comment by kamil-mrzyglod** [comment]
Implemented in #120
