### ISSUE TITLE
AKS cost estimate is too high

### ISSUE THREAD

**Issue by Gordonby** [TheCloudTheory/arm-estimator#149]
ref: https://github.com/Azure/AKS-Construction/actions/runs/3939658144/jobs/6739821204#step:6:134

```
    templateURL: https://github.com/Azure/AKS-Construction/releases/download/0.9.7/main.json
    paramsURL: https://raw.githubusercontent.com/Azure/AKS-Construction/gb-costestiamte/.github/workflows_dep/AksDeploy-ByoVnet.parameters.json
```

Estimate for a 4 node AKS cluster is $2.8M!

![image](https://user-images.githubusercontent.com/17914476/212949732-f05c81ac-ffb6-4d0b-8d0b-c54554e3367c.png)

![image](https://user-images.githubusercontent.com/17914476/212949475-ba29f371-83c9-4dbb-be30-ea8c9b539be5.png)

**Comment by kamil-mrzyglod** [comment]
It seems that reservation cost is being added to the calculation as result of invalid syntax when querying Retail API.
