### ISSUE TITLE
Add support for LogAnalytics workspace cap float number

### ISSUE THREAD

**Issue by michalchecinski** [TheCloudTheory/arm-estimator#180]
Setting the Log Analytics workspace cap to a float (like `0.1`) results in an error on the image below, although the resources with that value are deployed correctly. It's a broader problem since Microsoft doesn't use a float/double type for this entity, but since in the deployment it works fine, maybe there's a solution for it in the `WhatIf` scenario.

![image](https://user-images.githubusercontent.com/13666432/228679007-af880aa6-a5ef-4394-9d24-5fa898905215.png)

The bicep definition to reproduce that error:
```
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: 'logAnalyticsWorkspaceName'
  location: resourceGroup().location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 90
    workspaceCapping: {
      dailyQuotaGb: json('0.023')
    }
  }
}
```

**Comment by kamil-mrzyglod** [comment]
It might be possible to fix as it fails not on WhatIf operation, but rather the final estimation, where WhatIf result is deserialized to strongly-typed result containing quota value:

```
internal class WorkspaceCapping
{
    [JsonPropertyName("dailyQuotaGb")]
    public int DailyQuotaGB { get; set; }
}
```

Doesn't seem to be complicated.

**Comment by kamil-mrzyglod** [comment]
@michalchecinski Fixed, I'll let all the tests run and will publish new version tomorrow as the next 1.2 prerelease version. Official 1.2 will be released second half of April.
