### ISSUE TITLE
ACE Cost estimates mismatch with Azure Pricing calculator estimates

### ISSUE THREAD

**Issue by ajinkya101** [TheCloudTheory/arm-estimator#44]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### ACE Version

arm-estimator v1.0.0-alpha4

### ARM Template Configuration File

```JSON
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
      "_generator": {
        "name": "bicep",
        "version": "0.3.255.40792",
        "templateHash": "12664076982723927521"
      }
    },
    "functions": [],
    "resources": [
      {
        "type": "Microsoft.Web/serverfarms",
        "apiVersion": "2022-03-01",
        "name": "logicapp",
        "location": "westeurope",
        "sku": {
          "name": "WS1",
          "tier": "WorkflowStandard"
        },
        "properties": {}
      }
    ]
  }
```

### Expected Behavior

We should get same price in ACE tool with Azure Pricing calculator for Logic app Workflow "Standard Plan 1". Even if i check with plan 2 and 3, It also don't matches. Not able to understand how it's exactly working.

Click Me - > [Pricing calculator page](https://azure.com/e/e569095d23844c90984d0a9db20083e8)

### Actual Behavior

6. Run the Command
```
PS D:\Azure\Bicep\cost-estimates> arm-estimator .\logicapp.json <sub_id> azcost
```
7. Output
```
Estimations:

-> [Create] logicapp (Microsoft.Web/serverfarms) [Total cost: 152.14 USD | Delta: +152.14 USD]

Aggregated metrics:

-> Standard | Logic Apps | vCPU Duration | 0.1972 for 1 Hour
-> Standard | Logic Apps | Memory Duration | 0.0141 for 1 GiB Hour

-------------------------------

Summary:

-> Total cost: 152.14 USD
-> Delta: +152.14 USD
```

**Comment by kamil-mrzyglod** [comment]
I'll check that but can you verify if you're using correct licensing program when using Pricing Calculator?
![image](https://user-images.githubusercontent.com/11725731/184530918-6526c3f0-9f44-489e-a8d4-b7f45e8ddf21.png)

**Comment by ajinkya101** [comment]
@kamil-mrzyglod , I am unable to find `Microsoft Online Services Agreement`. The only option which I see is `Microsoft Customer Agreement` which is part of (CSP Program), where Microsoft partner company orders and provision the subscription to the customer like what we used to do.

**Comment by kamil-mrzyglod** [comment]
@ajinkya101 Are you signed in to the calculator? The reason I'm asking is because pricing an be different depending on the selected program.

**Comment by ajinkya101** [comment]
Oh, After signed in, Now I can see the option for `Microsoft Online Services Agreement`. But the pricing looks same for both program. The thing which is bothering also is with Workflow standard plan 3 there is huge difference in cost.

ACE tool - 456.41 USD
Pricing Calc - 719.93 USD

**Comment by kamil-mrzyglod** [comment]
Nonetheless, those reported metrics are the only metrics I found coming from the Retail API. Maybe Logic App cost is coming from additional metric I didn't took into consideration.

WS3 is indeed invalid. It's caused by the fact, that WS3 is 4x bigger than WS1 while I assumed 3x only.

**Comment by kamil-mrzyglod** [comment]
@ajinkya101 Okay, I found it - it's caused by invalid calculation made by ACE. Price is per vCore and per GiB, while ACE is just taking values as they are without multiplying by the number of allocated resources. It's going to be fixed soon.

**Comment by kamil-mrzyglod** [comment]
Extract after the fix:
```
-> [Create] logicapp (Microsoft.Web/serverfarms) [Total cost: 177.52 USD | Delta: +177.52 USD]

Aggregated metrics:

-> Standard | Logic Apps | vCPU Duration | 0.1972 for 1 Hour
-> Standard | Logic Apps | Memory Duration | 0.0141 for 1 GiB Hour

-> [Create] logicapp22 (Microsoft.Web/serverfarms) [Total cost: 355.03 USD | Delta: +355.03 USD]

Aggregated metrics:

-> Standard | Logic Apps | vCPU Duration | 0.1972 for 1 Hour
-> Standard | Logic Apps | Memory Duration | 0.0141 for 1 GiB Hour

-> [Create] logicapp222 (Microsoft.Web/serverfarms) [Total cost: 710.06 USD | Delta: +710.06 USD]

Aggregated metrics:

-> Standard | Logic Apps | vCPU Duration | 0.1972 for 1 Hour
-> Standard | Logic Apps | Memory Duration | 0.0141 for 1 GiB Hour
```

The rest of the difference comes from the fact that ACE is assuming 720hrs per month while Pricing Calculator takes 730hrs by default. It's up to decide later which value seems more correct.
