### ISSUE TITLE
Containerization instead of exe?

### ISSUE THREAD

**Issue by torivara** [TheCloudTheory/arm-estimator#57]
Hi! 👋 

This project looks promising, but I am usually extremely careful around unknown executables. As far as I can see, you are working with .Net 6.0, and this is .Net Core, am I right?

In that regard, would it be a huge task for you to containerize this and run it in a simple container image? Could maybe increase adoption and reduce the user risk?

Just an improvement suggestion! I love the open source community! ❤️‍🔥

**Comment by kamil-mrzyglod** [comment]
Hi @torivara!

Thank you for your feedback. Actually containerization was something I was thinking about, but as the next step. I guess I can work on it to have it completed for `1.0` milestone.

**Comment by kamil-mrzyglod** [comment]
@torivara One more question - are you looking for ability to run a Docker image directly from a source (build & run) or running it from a public source like Docker Hub?

**Comment by kamil-mrzyglod** [comment]
Docker image is now available - https://hub.docker.com/r/thecloudtheory/azure-cost-estimator
