### ISSUE TITLE
Parametrized OS type blocks VM estimation

### ISSUE THREAD

**Issue by PiotrWachulec** [TheCloudTheory/arm-estimator#93]
Hi @kamil-mrzyglod!

I tested your ARM estimation and I met one issue. I have a generalized template for VM deployment with OS type chosen based on parameters values and during running the ARM estimator I got the below error:
`[Error] Can't create a filter for Virtual Machine when VM size or OS is unavailable.`
It looks that based on VM and params ARM estimator can't decide which OS will be chosen. Maybe it's an area to make improvements :)

Cheers!
Piotr

**Comment by kamil-mrzyglod** [comment]
Hey @PiotrWachulec!

Azure VM support may be still a little bit "lacking" as that's something I've planned to do in the upcoming weeks. If you could provide template you used and exact output from ACE, it'll help in finding an issue.
